### ISSUE TITLE
three zipped bundles have wrong pdfs for 6x9 pages

### ISSUE THREAD

**Issue by GWMarvelle** [hymns-for-worship/issues#111]
Just to let you know,
These 3 have pdfs of either the powerpoint title slide or verse slide instead of the "print small" 6x9 page pdfs.

#73 Sweet Hour of Prayer:
000000000000079.zip

#459 The Precious Book Divine
000000000000466.zip
(also, only 1 verse of powerpoint slides)

#20203 Immanuel, God with Us
000000000001213.zip

**Comment by DSCOBURN** [comment]
Rody this has been corrected.

**Comment by GWMarvelle** [comment]
These 3 also have slide images instead of the 6x9 & "Print Small" pdfs.  That is, when you open the 6x9 or "Print Small" pdfs, instead of the score page, there is either the title card slide or verse slide inside the pdf.
20709 Father, Help Us Remember
21790 There's a Home
21921 I Surrender All  -- No PDF score fpr 8.5x11 or 6x9

The aforementioned still appear to be true of the bundles, at least in in these locations:
#73 Sweet Hour of Prayer:
hymns-for-worship.fra1.cdn.digitaloceanspaces.com/bundles/000000000000079.zip
#459 The Precious Book Divine
hymns-for-worship.fra1.cdn.digitaloceanspaces.com/bundles/000000000000466.zip
(only 1 verse)
20203 Immanuel, God with Us
hymns-for-worship.fra1.cdn.digitaloceanspaces.com/bundles/000000000001213.zip

**Comment by DSCOBURN** [comment]
I have checked these out and they all look correct. Delete cache in app settings, then reopen app

**Comment by rodydavis** [comment]
Is this still the case on the latest?

**Comment by DSCOBURN** [comment]
I would call it complete.
